name: weather_plan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^0.13.6
  firebase_core: ^2.25.4
  firebase_database: ^10.3.7
  flutter_local_notifications: ^17.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  weather: ^3.0.0
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF

    - family: Inter
      fonts:
        - asset: assets/fonts/inter-light.TTF
