// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHKIceJ-24Jv4ssE05dBPDCRkHdLn_uY',
    appId: '1:866111456899:web:b36af02af4dbec6c237db6',
    messagingSenderId: '866111456899',
    projectId: 'weatherplan-be037',
    authDomain: 'weatherplan-be037.firebaseapp.com',
    storageBucket: 'weatherplan-be037.firebasestorage.app',
    measurementId: 'G-D1GB1YLFVF',
    databaseURL:
        'https://weatherplan-be037-default-rtdb.asia-southeast1.firebasedatabase.app/ ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ieJtrA_F5eoRQKnJ8A955I4_Imixte4',
    appId: '1:866111456899:android:4bc9ca31d2f11581237db6',
    messagingSenderId: '866111456899',
    projectId: 'weatherplan-be037',
    storageBucket: 'weatherplan-be037.firebasestorage.app',
    databaseURL:
        'https://weatherplan-be037-default-rtdb.asia-southeast1.firebasedatabase.app/ ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBiKcu3wcR8GXbSQGJeFVAqedmJOmQ2X0',
    appId: '1:866111456899:ios:d9465945ddcf818f237db6',
    messagingSenderId: '866111456899',
    projectId: 'weatherplan-be037',
    storageBucket: 'weatherplan-be037.firebasestorage.app',
    iosBundleId: 'com.example.weatherPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBiKcu3wcR8GXbSQGJeFVAqedmJOmQ2X0',
    appId: '1:866111456899:ios:d9465945ddcf818f237db6',
    messagingSenderId: '866111456899',
    projectId: 'weatherplan-be037',
    storageBucket: 'weatherplan-be037.firebasestorage.app',
    iosBundleId: 'com.example.weatherPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOHKIceJ-24Jv4ssE05dBPDCRkHdLn_uY',
    appId: '1:866111456899:web:5a7bf71832ae902a237db6',
    messagingSenderId: '866111456899',
    projectId: 'weatherplan-be037',
    authDomain: 'weatherplan-be037.firebaseapp.com',
    storageBucket: 'weatherplan-be037.firebasestorage.app',
    measurementId: 'G-7CBMNQ9ZW5',
  );
}
